# Introduction to NumPy (numeric Python) for the Image processing class

## NumPy, SciPy (Scientific Python) and MatPlotLib (Mathematic plotting library) = replacement of Matlab 

Numpy is not native, hence we need to import it:

In [2]:
import numpy as np

## Numpy implements nd-arrays (which can be images)

In [3]:
a = np.zeros((2,3))

shape and dtype 

In [4]:
print(a.shape)
print(a.dtype)
a

(2, 3)
float64


array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
a = np.ones((2,1))
a

array([[1.],
       [1.]])

In [6]:
a = np.ones((2,1),dtype=int)
a

array([[1],
       [1]])

In [7]:
a = np.full((2,2),7.)
a

array([[7., 7.],
       [7., 7.]])

In [8]:
a = np.eye(3) # identity matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create random numbers between 0 and 1

In [9]:
a = np.random.random((3,2))
a

array([[0.55138052, 0.33165654],
       [0.94713208, 0.96812048],
       [0.87842363, 0.83266018]])

and Gaussian random numbers with std=1 and mean = 0

In [10]:
a = np.random.randn(3,2) # parameter is not shape as an object but content of shape
a

array([[ 0.15391407, -0.14134898],
       [-1.51905937,  0.55790291],
       [ 0.21843942,  0.77258285]])

## Ordered numbers (linspace and arange)

Create 10 elements between 0 and 1, i element [0,1]:

In [11]:
ar = np.linspace(0,1,10)
ar

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [12]:
ar = np.linspace(0,1) # default: 50 elements
ar.shape

(50,)

Create elements between 0 and 1 with offset 0.1, i element [0,1[: 

In [13]:
ar = np.arange(0,1,0.1)
ar

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [14]:
ar = np.arange(10) # default: start at 0 and offset 1
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Combine two arrays

In [15]:
ar = np.arange(10)+np.arange(10)
ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Combine array with scalar:

In [16]:
ar = np.arange(10)+1
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Ordered nd-arrays (meshgrid and mgrid):

In [17]:
x = np.arange(5) # 0,1,2,3,4
y = np.arange(3) # 0,1,2
xv, yv = np.meshgrid(x, y)
xv

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [18]:
yv

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])

Compute the Euclidean distance of each pixel from the upper corner: 

In [19]:
dist = (xv**2+yv**2)**0.5
dist

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595]])

## Array indexing:

In [55]:
ar1D = np.arange(12)
ar = ar1D.reshape((3,4)) # reindexing (not copying) of the matrix  
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
ar[:,0] = -1
ar

array([[-1,  1,  2,  3],
       [-1,  5,  6,  7],
       [-1,  9, 10, 11]])

! The 2D matrix is just a "view" of the 1D array !

In [22]:
ar1D

array([-1,  1,  2,  3, -1,  5,  6,  7, -1,  9, 10, 11])

if you want to copy the matrix you must use the copy() function:

flat copy:

In [67]:
ar1 = np.arange(5)
ar2 = ar1
ar2[0] = 5
print(ar1)
print(ar2)

[5 1 2 3 4]
[5 1 2 3 4]


deep copy using copy() - function

In [68]:
ar1 = np.arange(5)
ar2 = ar1.copy()
ar2[0] = 5
print(ar1)
print(ar2)

[0 1 2 3 4]
[5 1 2 3 4]


In [60]:
ar[:] = -2
ar

array([[-2, -2, -2, -2],
       [-2, -2, -2, -2],
       [-2, -2, -2, -2]])

In [24]:
ar1D = np.arange(12)
ar = ar1D.reshape((3,4)) 
ar[1,0:2] = -1
ar

array([[ 0,  1,  2,  3],
       [-1, -1,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
ar[:,1:] = -3
ar

array([[ 0, -3, -3, -3],
       [-1, -3, -3, -3],
       [ 8, -3, -3, -3]])

## more about reshape

In [26]:
ar2 =ar.reshape(6,2)
ar2

array([[ 0, -3],
       [-3, -3],
       [-1, -3],
       [-3, -3],
       [ 8, -3],
       [-3, -3]])

In [27]:
ar2 = ar.reshape(4,-1) # -1 = placeholder for only valid number (here 3)
ar2

array([[ 0, -3, -3],
       [-3, -1, -3],
       [-3, -3,  8],
       [-3, -3, -3]])

In [28]:
ar2 = ar.reshape(2,-1,3,1) # reshape to 4 dimensional array (only one -1 is allowed)
ar2.shape

(2, 2, 3, 1)

In [29]:
ar2 = ar.reshape(-1) # most common use of -1
ar2.shape

(12,)

## Boolean indexing

In [30]:
ar1 = np.arange(12)
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
bool1 = ar1>2
bool1

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [32]:
bool2 = np.logical_and(ar1>2,ar1<8)
bool2

array([False, False, False,  True,  True,  True,  True,  True, False,
       False, False, False])

In [33]:
ar1[bool2]

array([3, 4, 5, 6, 7])

In [34]:
ar1[bool2] = -1
ar1

array([ 0,  1,  2, -1, -1, -1, -1, -1,  8,  9, 10, 11])

## More numpy commands:

### max, min, maximum, minimum, clip:

In [35]:
scalar1,scalar2  = 4,8
max(scalar1,scalar2) # this is not numpy!

8

maximum of an array (np.max):

In [36]:
ar1 = np.arange(12)
np.max(ar1)

11

pointwise maximum of two lists (np.maximum):

In [37]:
np.maximum(ar1,5) # list & scalar

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 11])

In [38]:
ar2 = ar1[-1::-1] # from -1 (end) for all with step size -1
ar2

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [39]:
np.maximum(ar1,ar2)

array([11, 10,  9,  8,  7,  6,  6,  7,  8,  9, 10, 11])

### Clipping:

In [40]:
np.minimum(np.maximum(ar1,2),8)

array([2, 2, 2, 3, 4, 5, 6, 7, 8, 8, 8, 8])

In [41]:
np.clip(ar1,2,8)

array([2, 2, 2, 3, 4, 5, 6, 7, 8, 8, 8, 8])

### Many commands exist in Python for the same thing: Try to be consistent in your code

In [42]:
ar1*ar1

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [43]:
ar1**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [44]:
np.square(ar1)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [45]:
np.power(ar1,2)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

### Other example: Square root

In [46]:
np.sqrt(ar1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [47]:
np.power(ar1,0.5)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [48]:
ar1**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

## Matrix operations:

In [49]:
ar1 = np.arange(9).reshape((3,3))

In [50]:
ar1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Pointwise product of two matrices

In [52]:
ar1 * np.eye(3)

array([[0., 0., 0.],
       [0., 4., 0.],
       [0., 0., 8.]])

Matrix product of two matrices

In [53]:
np.matmul(ar1,np.eye(3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

Dot product of two matrices 

In [54]:
np.vdot(ar1,np.eye(3)) # 0*1 + 4*1 + 8*1

12.0